Repository python/core-workflow, pull requests merged in 2018-06, with the labels that each got.

#252 Refactor Travis CI config
  .travis.yml
Labels: CI, CLA signed, configuration

#256 Add cherry_picker to CODEOWNERS
  .github/CODEOWNERS
Labels: CLA signed

#253 Support version retrieval from custom branches
  .gitignore
  cherry_picker/cherry_picker/cherry_picker.py
  cherry_picker/cherry_picker/test.py
  cherry_picker/readme.rst
Labels: CLA signed, cherry_picker.py

#261 Post-release changes.
  cherry_picker/cherry_picker/__init__.py
  cherry_picker/readme.rst
Labels: CLA signed, cherry_picker.py

#248 blurb: don't break after hyphens and too long words.
  blurb/blurb.py
  blurb/tests/pass/no-break-long-words.rst
  blurb/tests/pass/no-break-long-words.rst.res
  blurb/tests/pass/no-break-on-hyphens.rst
  blurb/tests/pass/no-break-on-hyphens.rst.res
Labels: CLA signed, blurb

#264 Explicit push location to ignore user git config
  cherry_picker/cherry_picker/cherry_picker.py
Labels: CLA signed

#271 Add zulipchat badge to readme
  README.rst
Labels: CLA signed
